# Generated by Django 5.1.3 on 2024-11-08 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Администратор'), ('PM1', 'Менеджер проекта'), ('PM2', 'Старший менеджер проекта'), ('EMP1', 'Сотрудник'), ('EMP2', 'Старший сотрудник'), ('DATA1', 'Аналититк'), ('DATA2', 'Старший аналитик'), ('DES1', 'Дизайнер'), ('DES2', 'Старший дизайнер'), ('DEV1', 'Разработчик'), ('DEV2', 'Старший разработчик'), ('QA1', 'Тестировщик'), ('QA2', 'Старший тестировщик')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='ongoing_projects',
            field=models.ManyToManyField(to='users.project'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ongoing_tasks',
            field=models.ManyToManyField(to='users.task'),
        ),
    ]
