# Generated by Django 5.1.3 on 2024-11-12 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_remove_user_projects_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ongoing_projects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ongoing_tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Администратор'), ('PM1', 'Менеджер проекта'), ('PM2', 'Старший менеджер проекта'), ('EMP1', 'Сотрудник'), ('EMP2', 'Старший сотрудник'), ('DATA1', 'Аналититк'), ('DATA2', 'Старший аналитик'), ('DES1', 'Дизайнер'), ('DES2', 'Старший дизайнер'), ('DEV1', 'Разработчик'), ('DEV2', 'Старший разработчик'), ('QA1', 'Тестировщик'), ('QA2', 'Старший тестировщик')], max_length=150),
        ),
    ]
