# Generated by Django 5.1.3 on 2024-11-13 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Администратор'), ('PM1', 'Менеджер проекта'), ('PM2', 'Старший менеджер проекта'), ('EMP1', 'Сотрудник'), ('EMP2', 'Старший сотрудник'), ('DATA1', 'Аналитик'), ('DATA2', 'Старший аналитик'), ('DES1', 'Дизайнер'), ('DES2', 'Старший дизайнер'), ('DEV1', 'Разработчик'), ('DEV2', 'Старший разработчик'), ('QA1', 'Тестировщик'), ('QA2', 'Старший тестировщик')], max_length=150),
        ),
    ]
